extraction:
libssl-dev
  cpp:
    prepare:
      packages:
        - libssl-dev
        - cmake
#    after_prepare:
#      - curl -LO https://github.com/Kitware/CMake/releases/download/v3.19.5/cmake-3.19.5.tar.gz
#      - tar -xf cmake-3.19.5.tar.gz
#      - pushd cmake-3.19.5
#      - ./bootstrap
#      - make
#      - popd
#      - export PATH=$PWD/cmake-3.19.5/bin:$PATH